/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorabasica.pineda;

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalc extends javax.swing.JFrame {

    //VARIABLES PUBLICAS,PRIVADAS,GLOBALES Y GENERICAS
    private String entrada= "";
    private int numero1, numero2;
    private String operador;
    
    public jfrmCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn7 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnborrar = new javax.swing.JButton();
        jbtnsuma = new javax.swing.JButton();
        jbtnresta = new javax.swing.JButton();
        jbtnmulti = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtndivi = new javax.swing.JButton();
        jbtnigual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jtxtCantidad.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N

        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnborrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnborrar.setText("AC");
        jbtnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnborrarActionPerformed(evt);
            }
        });

        jbtnsuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnsuma.setText("+");
        jbtnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsumaActionPerformed(evt);
            }
        });

        jbtnresta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnresta.setText("-");
        jbtnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrestaActionPerformed(evt);
            }
        });

        jbtnmulti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnmulti.setText("*");
        jbtnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtndivi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtndivi.setText("/");
        jbtndivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndiviActionPerformed(evt);
            }
        });

        jbtnigual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnigual.setText("=");
        jbtnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnigualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCantidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnmulti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtndivi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn0))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn1)
                                .addGap(12, 12, 12)
                                .addComponent(jbtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn3)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtn7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtn8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtn9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnborrar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtn4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtn5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtn6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7)
                    .addComponent(jbtn8)
                    .addComponent(jbtn9)
                    .addComponent(jbtnborrar))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn6)
                    .addComponent(jbtn5)
                    .addComponent(jbtn4)
                    .addComponent(jbtnsuma))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtn2)
                                .addComponent(jbtn3)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnresta)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn1)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndivi)
                    .addComponent(jbtn0)
                    .addComponent(jbtnmulti)
                    .addComponent(jbtnigual))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +7;
        jtxtCantidad.setText(entrada);
        
        
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         // LLAMAR Y CAPTURAR UN DATO UWU
        //IMPRIMIR
        entrada = entrada +0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumaActionPerformed
        //CAPTURAR Y CONVERTIR EL TEXTO A UN VALOR
        //LIMPIAR LA CAJA DE TEXTO
        //CPATURAR EL SIGNO= OPERAR
        //ENVIAR EN PANTALÑAÑP LO QUE CAPTURADO EN ENTRADA
        
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="+";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnsumaActionPerformed

    private void jbtnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestaActionPerformed
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="-";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnrestaActionPerformed

    private void jbtnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiActionPerformed
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="*";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnmultiActionPerformed

    private void jbtndiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndiviActionPerformed
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="/";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtndiviActionPerformed

    private void jbtnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnigualActionPerformed
        numero2=Integer.parseInt(entrada);
        jtxtCantidad.setText("");
        entrada= "";
        double resultado;
        if (operador.equals("+")){
            resultado= numero1+numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
        if (operador.equals("-")){
            resultado= numero1-numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
        if (operador.equals("*")){
            resultado= numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
        if (operador.equals("/")){
            resultado= numero1/numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        }
    }//GEN-LAST:event_jbtnigualActionPerformed

    private void jbtnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnborrarActionPerformed
        entrada="0";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnborrar;
    private javax.swing.JButton jbtndivi;
    private javax.swing.JButton jbtnigual;
    private javax.swing.JButton jbtnmulti;
    private javax.swing.JButton jbtnresta;
    private javax.swing.JButton jbtnsuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
